name: ScoreboardLib
version: 1.2.0
description: Utilizing scoreboards for a UI enhancement.
authors:
  - TigerHix
  - Tigerpanzer_02
  - Plugily Projects
main: me.tigerhix.lib.scoreboard.ScoreboardLib