name: ScoreboardLib
version: ${version}
description: Utilizing scoreboards for a UI enhancement.
authors:
  - TigerHix
  - Tigerpanzer_02
  - Plugily Projects
main: me.tigerhix.lib.scoreboard.ScoreboardLib