name: Bump and Publish Master Branch

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
jobs:
  bump:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Commit
        uses: actions/checkout@v2
      - name: Bump Version
        id: bump
        uses: Plugily-Projects/version-bump-action@development
        with:
          github-token: ${{ secrets.github_token }}
          repo-build: GRADLE
          auto-version-bump: false
          auto-version-bump-release: true
      - name: Print Version
        run: "echo 'New Version: ${{steps.bump.outputs.version}}'"
  publish:
    if: github.event.pull_request.merged
    needs: bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 18
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish with Gradle
        run: ./gradlew build publishMavenPublicationToReleasesRepository
        env:
          SnapshotsUsername: ${{ secrets.SNAPSHOTSUSERNAME }}
          SnapshotsPassword: ${{ secrets.SNAPSHOTSPASSWORD }}