# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

# NO BUMP UNTIL FIRST RELEASE OF A PLUGIN!
#     - name: Bump Version
#        id: bump
#        uses: Plugily-Projects/maven-version-bump-action@dev
#        with:
#          github-token: ${{ secrets.github_token }}

      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.6.3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          java-package: jdk

      - name: maven-settings-action
        uses: s4u/maven-settings-action@v2.5.0
        with:
          servers: |
            [{
                "id": "${{ secrets.PLUGILY_REPO_ID }}",
                "username": "${{ secrets.PLUGILY_REPO_USERNAME }}",
                "password": "${{ secrets.PLUGILY_REPO_PASSWORD }}"
            }]
            
      - run: mvn clean verify compile package site:site javadoc:javadoc javadoc:jar deploy -f pom.xml
